feat: Zarf deploy-time GPU configuration
defenseunicorns/leapfrogai-backend-whisper pull request #28
Opened 2024-02-01 00:02 UTC by justinthelaw

- Collapses everything into 1 image for CPU and GPU support
- Zarf deployment allocated GPU based on GPU_ENABLED flag

2024-02-01 18:43 UTC, gphorvath approved these changes

2024-02-01 18:48 UTC, gphorvath approved these changes

2024-02-01 18:48 UTC, YrrepNoj commented on .python-version
> +3.11.6
gitignore please <3

2024-02-01 18:52 UTC, gphorvath commented on .python-version
> +3.11.6
Fixed.

2024-02-01 18:53 UTC, gphorvath submitted a review, later dismissed

2024-02-01 18:54 UTC, YrrepNoj requested changes

2024-02-01 18:54 UTC, YrrepNoj commented on zarf.yaml
> +              if [ "${ZARF_VAR_GPU_ENABLED}" = "true" ]; then kubectl patch deployment whisper-model-whisper -n leapfrogai --patch '{"spec":{"template":{"spec":{"containers":[{"name":"leapfrogai-mode
I think this logic should be handled as a helm template and not as an after-action patch.

You can template helm things (in this case it will be the container spec) to be conditional depending on the value of a variable.

[Here is an example](https://github.com/defenseunicorns/leapfrogai-api/blob/15c37e9516a589789d9b36d8927f5a2ea87d5ab3/chart/templates/vs.yaml#L1C1-L2C1)

2024-02-01 18:54 UTC, YrrepNoj commented on Makefile
> +docker-publish:
When would we use this vs using `make docker-build docker-push`?

2024-02-01 18:59 UTC, gphorvath commented on zarf.yaml
> +              if [ "${ZARF_VAR_GPU_ENABLED}" = "true" ]; then kubectl patch deployment whisper-model-whisper -n leapfrogai --patch '{"spec":{"template":{"spec":{"containers":[{"name":"leapfrogai-mode
This can be done in a future PR.

2024-02-01 19:00 UTC, gphorvath commented on Makefile
> +docker-publish:
deleted

2024-02-01 19:00 UTC, gphorvath submitted a review, later dismissed

2024-02-01 19:03 UTC, gerred commented on zarf.yaml
> +              if [ "${ZARF_VAR_GPU_ENABLED}" = "true" ]; then kubectl patch deployment whisper-model-whisper -n leapfrogai --patch '{"spec":{"template":{"spec":{"containers":[{"name":"leapfrogai-mode
I think this is a small enough fix to add into the Helm chart now so we don't keep the cognitive overhead of maintaining an issue or knowing we need to fix it unless there's a pressing need. If we really want to fix this in a future PR and it's a blocker to not have this PR in, can we open that draft PR now and track it to fix ASAP?

2024-02-01 19:04 UTC, gerred commented on zarf.yaml
> +              if [ "${ZARF_VAR_GPU_ENABLED}" = "true" ]; then kubectl patch deployment whisper-model-whisper -n leapfrogai --patch '{"spec":{"template":{"spec":{"containers":[{"name":"leapfrogai-mode
The problem is that this is introducing a race condition - patching the deployment doesn't ALWAYS restart the pod.

2024-02-06 07:37 UTC, YrrepNoj requested changes

2024-02-06 07:37 UTC, YrrepNoj commented on zarf.yaml
> +      url: oci://ghcr.io/defenseunicorns/packages/leapfrogai/leapfrogai-model:0.5.0-skeleton
This tag does not exist, were you working off a skeleton on your local daemon? Looks like this is related to https://github.com/defenseunicorns/leapfrog-model-skeleton/pull/13.

Leaving this comment here to make sure we don't merge this before the linked PR is merged and released/published.

2024-02-06 07:37 UTC, YrrepNoj commented on Makefile
> +VERSION ?= $(shell git fetch --tags && git tag -l "*.*.*" | sort -V | tail -n 1 | sed -e 's/^v//')
This command seems pretty complex. Can you help me understand what you're trying to achieve that the old shell command wasn't?

I see that we're sed'ing out the `v` in the tag, but what's the motivation behind everything else?

2024-02-06 07:37 UTC, YrrepNoj commented on Makefile
> +docker-build-gpu:
The targets `docker-build-gpu` and `docker-push-gpu` should be removed since we're removing the `Dockerfile.gpu`.

2024-02-06 14:48 UTC, justinthelaw commented on Makefile
> +VERSION ?= $(shell git fetch --tags && git tag -l "*.*.*" | sort -V | tail -n 1 | sed -e 's/^v//')
(answered via Slack) Yes, I want to keep this part intact until I make a branch for workflows. I can remove this from this PR to keep this PR's footprint smaller

2024-02-07 19:37 UTC, YrrepNoj reviewed
misc comments and thoughts <3

2024-02-07 19:37 UTC, YrrepNoj commented on .github/workflows/release-docker-build-push.yaml
> +        run: echo "VERSION=$(git describe --abbrev=0 --tags | sed -e 's/^v//')" >> $GITHUB_ENV
Github has a builtin secret [$GITHUB_REF_NAME](https://docs.github.com/en/actions/learn-github-actions/variables#:~:text=branch%2D1.-,GITHUB_REF_NAME,-The%20short%20ref) that we should use instead of `git describe --abbrev=0 --tags`.

2024-02-07 19:37 UTC, YrrepNoj commented on pyproject.toml
> +requires-python = ">=3.11.4, <3.12"
Can we pin to 3.11.6?

2024-02-10 04:15 UTC, YrrepNoj approved these changes

2024-02-10 13:51 UTC, merged